name: Test R-universe
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: zqzneptune
